# Site settings
title: Privilege Now
email: hello@privilegenow.org
description: privilegenow
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://privilegenow.org" # the base hostname & protocol for your site
twitter_username: privilegenow
github_username:  privilegenow

# Build settings
markdown: kramdown
