# Site settings
title: Token Male
email: hello@tokenmale.org
description: Token Male
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tokenmale.org" # the base hostname & protocol for your site
twitter_username: tokenmale
github_username:  tokenmale

# Build settings
markdown: kramdown
